-- ============================================================
-- Seed: 70 demo events with banner + gallery images
-- banner: 1200x400  |  gallery images: 800x600 each (3 per event)
-- Run against your Railway PostgreSQL database:
--   psql $DATABASE_URL -f seed_events.sql
-- ============================================================

INSERT INTO events (
    id, title, description, hosted_by, host_type, organizer_name,
    mode, location, meeting_url, start_at, end_at,
    tags, is_active, risk_score, risk_level, risk_reasons,
    banner_url, image_urls, created_at, modified_at
) VALUES

-- ── Career & Internship (1-12) ────────────────────────────────────────────────
(gen_random_uuid(), 'Spring Career Fair 2026', 'Connect with 80+ top employers from tech, finance, healthcare, and engineering. Bring your resume and dress professionally. Open to all graduate students.', 'demo-admin-001', 'admin', 'MSU Career Center', 'in_person', 'Lee Hall Ballroom, Mississippi State University', NULL, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days 6 hours', ARRAY['career','internship','networking','jobs'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/careerfair/1200/400', ARRAY['https://picsum.photos/seed/careerfaira/800/600','https://picsum.photos/seed/careerfairb/800/600','https://picsum.photos/seed/careerfairc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Tech Industry Networking Night', 'An exclusive evening with engineers and recruiters from Google, Microsoft, Amazon, and 15 other tech companies. Light refreshments provided.', 'demo-admin-001', 'admin', 'MSU Engineering Career Services', 'in_person', 'Engineering Research Center, Room 101', NULL, NOW() + INTERVAL '9 days', NOW() + INTERVAL '9 days 3 hours', ARRAY['tech','networking','career','jobs'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/technight/1200/400', ARRAY['https://picsum.photos/seed/technighta/800/600','https://picsum.photos/seed/technightb/800/600','https://picsum.photos/seed/technightc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Resume & LinkedIn Workshop', 'Professional coaches review your resume live and give personalized feedback. Learn how to optimize your LinkedIn profile to attract recruiters. Limited to 30 attendees.', 'demo-admin-001', 'admin', 'Graduate School Professional Development', 'hybrid', 'Allen Hall 204', 'https://zoom.us/j/demo123', NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days 2 hours', ARRAY['resume','linkedin','career','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/resumews/1200/400', ARRAY['https://picsum.photos/seed/resumewsa/800/600','https://picsum.photos/seed/resumewsb/800/600','https://picsum.photos/seed/resumewsc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Internship Panel: Life at a Startup vs Big Tech', 'Hear from recent alumni who interned at startups, mid-size companies, and FAANG. Q&A session included.', 'demo-admin-001', 'admin', 'MSU Alumni Network', 'virtual', NULL, 'https://zoom.us/j/demo456', NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days 2 hours', ARRAY['internship','panel','startup','bigtech','career'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/internpanel/1200/400', ARRAY['https://picsum.photos/seed/internpanela/800/600','https://picsum.photos/seed/internpanelb/800/600','https://picsum.photos/seed/internpanelc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Mock Interview Day', 'Practice behavioral and technical interviews with industry professionals. Get real-time feedback and tips to ace your next interview. Sign up for a 30-minute slot.', 'demo-admin-001', 'admin', 'Career Development Office', 'in_person', 'Colvard Student Union, Room 302', NULL, NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days 8 hours', ARRAY['interview','career','practice','skills'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/mockinterview/1200/400', ARRAY['https://picsum.photos/seed/mockinterviewa/800/600','https://picsum.photos/seed/mockinterviewb/800/600','https://picsum.photos/seed/mockinterviewc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Federal Government Careers Info Session', 'Learn about internship and full-time opportunities with NASA, NSF, USDA, and other federal agencies. Security clearance roles also discussed.', 'demo-admin-001', 'admin', 'MSU Career Center', 'hybrid', 'Mitchell Memorial Library, Conf Room A', 'https://teams.microsoft.com/demo', NOW() + INTERVAL '18 days', NOW() + INTERVAL '18 days 2 hours', ARRAY['government','federal','career','internship'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/govtcareers/1200/400', ARRAY['https://picsum.photos/seed/govtcareersa/800/600','https://picsum.photos/seed/govtcareersb/800/600','https://picsum.photos/seed/govtcareersc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Salary Negotiation Masterclass', 'Know your worth. Learn evidence-based strategies to negotiate your first offer and subsequent raises. Includes role-play exercises.', 'demo-admin-001', 'admin', 'Graduate Professional Development', 'virtual', NULL, 'https://zoom.us/j/demo789', NOW() + INTERVAL '21 days', NOW() + INTERVAL '21 days 90 minutes', ARRAY['salary','negotiation','career','finance'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/salaryneg/1200/400', ARRAY['https://picsum.photos/seed/salarynega/800/600','https://picsum.photos/seed/salarynegb/800/600','https://picsum.photos/seed/salarynegc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Healthcare & Biotech Career Expo', 'Meet recruiters from hospitals, pharmaceutical companies, biotech startups, and research institutions. Graduate students in health sciences encouraged.', 'demo-admin-001', 'admin', 'College of Veterinary Medicine', 'in_person', 'Wise Center, Main Hall', NULL, NOW() + INTERVAL '25 days', NOW() + INTERVAL '25 days 5 hours', ARRAY['healthcare','biotech','career','pharma'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/healthcareer/1200/400', ARRAY['https://picsum.photos/seed/healthcareera/800/600','https://picsum.photos/seed/healthcareerb/800/600','https://picsum.photos/seed/healthcareerc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'On-Campus Recruiting: Software Engineering Roles', 'Top tech companies conducting on-site interviews. Apply in advance through Handshake. Spots are first-come-first-served.', 'demo-admin-001', 'admin', 'MSU Career Center', 'in_person', 'McCain Engineering Building', NULL, NOW() + INTERVAL '30 days', NOW() + INTERVAL '30 days 6 hours', ARRAY['internship','software','recruiting','tech'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/oncampus/1200/400', ARRAY['https://picsum.photos/seed/oncampusa/800/600','https://picsum.photos/seed/oncampusb/800/600','https://picsum.photos/seed/oncampusc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Data Science Career Paths Panel', 'Four professionals share their journey from graduate school to data science roles in industry, academia, and government.', 'demo-admin-001', 'admin', 'Department of Computer Science', 'virtual', NULL, 'https://zoom.us/j/ds-panel', NOW() + INTERVAL '11 days', NOW() + INTERVAL '11 days 2 hours', ARRAY['data science','career','panel','machine learning'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/datascicareer/1200/400', ARRAY['https://picsum.photos/seed/datascicareera/800/600','https://picsum.photos/seed/datascicareerb/800/600','https://picsum.photos/seed/datascicareerc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'International Student Job Search Strategies', 'Navigating the US job market as an international student — OPT, CPT, H1B sponsorship, and employer outreach tips.', 'demo-admin-001', 'admin', 'International Student Services', 'hybrid', 'Montgomery Hall 108', 'https://zoom.us/j/intl-careers', NOW() + INTERVAL '16 days', NOW() + INTERVAL '16 days 2 hours', ARRAY['international','visa','career','opt','cpt'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/intljob/1200/400', ARRAY['https://picsum.photos/seed/intljoba/800/600','https://picsum.photos/seed/intljobb/800/600','https://picsum.photos/seed/intljobc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'LinkedIn Headshot & Profile Day', 'Get a free professional headshot and have your LinkedIn profile reviewed by career coaches. Walk-ins welcome.', 'demo-admin-001', 'admin', 'MSU Career Center', 'in_person', 'Career Center Lobby', NULL, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days 4 hours', ARRAY['linkedin','career','headshot','profile'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/headshot/1200/400', ARRAY['https://picsum.photos/seed/headshota/800/600','https://picsum.photos/seed/headshotb/800/600','https://picsum.photos/seed/headshotc/800/600'], NOW(), NOW()),

-- ── Tech Talks & Workshops (13-25) ─────────────────────────────────────────
(gen_random_uuid(), 'Intro to Machine Learning with Python', 'Hands-on workshop covering scikit-learn, pandas, and matplotlib. Build your first classification model. Bring your laptop with Python 3.10+ installed.', 'demo-univ-001', 'university', 'MSU Computer Science Department', 'in_person', 'Butler Hall 301, MSU', NULL, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days 3 hours', ARRAY['python','machine learning','workshop','ai'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/mlworkshop/1200/400', ARRAY['https://picsum.photos/seed/mlworkshopa/800/600','https://picsum.photos/seed/mlworkshopb/800/600','https://picsum.photos/seed/mlworkshopc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Cloud Computing on AWS: From Zero to Deploy', 'Learn EC2, S3, Lambda, and RDS basics. Deploy a full-stack app on AWS by the end of this workshop. AWS Free Tier account required.', 'demo-univ-001', 'university', 'MSU Computer Science Department', 'hybrid', 'Butler Hall 202', 'https://zoom.us/j/aws-workshop', NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days 4 hours', ARRAY['aws','cloud','devops','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/awscloud/1200/400', ARRAY['https://picsum.photos/seed/awsclouda/800/600','https://picsum.photos/seed/awscloudb/800/600','https://picsum.photos/seed/awscloudc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Introduction to Large Language Models', 'Explore how GPT, Claude, and Llama work under the hood. Topics: transformers, fine-tuning, prompt engineering, and RAG architectures.', 'demo-univ-001', 'university', 'AI Research Lab @ MSU', 'virtual', NULL, 'https://zoom.us/j/llm-intro', NOW() + INTERVAL '12 days', NOW() + INTERVAL '12 days 2 hours', ARRAY['llm','ai','nlp','gpt','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/llmtalk/1200/400', ARRAY['https://picsum.photos/seed/llmtalka/800/600','https://picsum.photos/seed/llmtalkb/800/600','https://picsum.photos/seed/llmtalkc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Cybersecurity CTF Workshop', 'Capture the Flag practice session. Topics: web vulnerabilities, reverse engineering, and cryptography basics. Great prep for real CTF competitions.', 'demo-univ-001', 'university', 'MSU Cybersecurity Club', 'in_person', 'Simrall Engineering, Lab 105', NULL, NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days 4 hours', ARRAY['cybersecurity','ctf','hacking','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/ctfworkshop/1200/400', ARRAY['https://picsum.photos/seed/ctfworkshopa/800/600','https://picsum.photos/seed/ctfworkshopb/800/600','https://picsum.photos/seed/ctfworkshopc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Git & GitHub for Graduate Researchers', 'Version control is essential for research. Learn branching, pull requests, CI/CD basics, and how to open-source your research code.', 'demo-univ-001', 'university', 'MSU Research Computing', 'hybrid', 'Digital Media Center, Room 220', 'https://teams.microsoft.com/git-workshop', NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days 2 hours', ARRAY['git','github','version control','research'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/gitworkshop/1200/400', ARRAY['https://picsum.photos/seed/gitworkshopa/800/600','https://picsum.photos/seed/gitworkshopb/800/600','https://picsum.photos/seed/gitworkshopc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Building REST APIs with FastAPI', 'From zero to production: design, build, test, and document a REST API using FastAPI, SQLAlchemy, and PostgreSQL.', 'demo-univ-001', 'university', 'MSU Computer Science Department', 'in_person', 'Butler Hall 301', NULL, NOW() + INTERVAL '20 days', NOW() + INTERVAL '20 days 3 hours', ARRAY['fastapi','python','api','backend','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/fastapiws/1200/400', ARRAY['https://picsum.photos/seed/fastapiwsa/800/600','https://picsum.photos/seed/fastapiwsb/800/600','https://picsum.photos/seed/fastapiwsc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'React & TypeScript for Beginners', 'Build a functional web app from scratch using React 18 and TypeScript. Covers hooks, state management, and API integration.', 'demo-univ-001', 'university', 'MSU Web Dev Club', 'hybrid', 'Hand Lab 105', 'https://zoom.us/j/react-ts', NOW() + INTERVAL '22 days', NOW() + INTERVAL '22 days 3 hours', ARRAY['react','typescript','frontend','workshop'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/reactws/1200/400', ARRAY['https://picsum.photos/seed/reactwsa/800/600','https://picsum.photos/seed/reactwsb/800/600','https://picsum.photos/seed/reactwsc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'DevOps & Kubernetes Fundamentals', 'Containers, orchestration, and CI/CD pipelines explained. Hands-on with Docker and Kubernetes using a local minikube cluster.', 'demo-univ-001', 'university', 'MSU Cloud Computing Group', 'virtual', NULL, 'https://zoom.us/j/k8s-basics', NOW() + INTERVAL '26 days', NOW() + INTERVAL '26 days 3 hours', ARRAY['kubernetes','docker','devops','cicd'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/devopsws/1200/400', ARRAY['https://picsum.photos/seed/devopswsa/800/600','https://picsum.photos/seed/devopswsb/800/600','https://picsum.photos/seed/devopswsc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Data Visualization with D3.js', 'Create stunning interactive charts and dashboards using D3.js. Basic JavaScript knowledge required.', 'demo-univ-001', 'university', 'MSU Data Science Club', 'in_person', 'Hand Lab 110', NULL, NOW() + INTERVAL '28 days', NOW() + INTERVAL '28 days 2 hours', ARRAY['d3','javascript','visualization','data'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/d3workshop/1200/400', ARRAY['https://picsum.photos/seed/d3workshopa/800/600','https://picsum.photos/seed/d3workshopb/800/600','https://picsum.photos/seed/d3workshopc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Mobile App Development with Flutter', 'Build cross-platform mobile apps that run on iOS and Android. Create a real app by the end of the session.', 'demo-univ-001', 'university', 'MSU Mobile Dev Club', 'hybrid', 'Simrall Hall 201', 'https://zoom.us/j/flutter-dev', NOW() + INTERVAL '33 days', NOW() + INTERVAL '33 days 3 hours', ARRAY['flutter','dart','mobile','android','ios'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/fluttermobile/1200/400', ARRAY['https://picsum.photos/seed/fluttermobilea/800/600','https://picsum.photos/seed/fluttermobileb/800/600','https://picsum.photos/seed/fluttermobilec/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Blockchain & Web3 for Developers', 'Demystifying blockchain technology. Build and deploy a smart contract on Ethereum testnet using Solidity.', 'demo-univ-001', 'university', 'MSU Fintech Club', 'virtual', NULL, 'https://zoom.us/j/web3-dev', NOW() + INTERVAL '35 days', NOW() + INTERVAL '35 days 2 hours', ARRAY['blockchain','web3','solidity','ethereum'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/web3solidity/1200/400', ARRAY['https://picsum.photos/seed/web3soliditya/800/600','https://picsum.photos/seed/web3solidityb/800/600','https://picsum.photos/seed/web3solidityc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'SQL & Database Design Deep Dive', 'Advanced SQL topics: window functions, CTEs, indexing strategies, query optimization, and database schema design patterns.', 'demo-univ-001', 'university', 'MSU Database Systems Group', 'in_person', 'Butler Hall 201', NULL, NOW() + INTERVAL '37 days', NOW() + INTERVAL '37 days 3 hours', ARRAY['sql','database','postgresql','optimization'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/sqldeep/1200/400', ARRAY['https://picsum.photos/seed/sqldeepa/800/600','https://picsum.photos/seed/sqldeepb/800/600','https://picsum.photos/seed/sqldeepc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Open Source Contribution Workshop', 'Find your first GitHub issue, fork a repo, and make your first pull request. Learn contributor etiquette and how to get involved with major open source projects.', 'demo-univ-001', 'university', 'MSU Open Source Club', 'hybrid', 'Digital Media Center 115', 'https://zoom.us/j/opensource', NOW() + INTERVAL '40 days', NOW() + INTERVAL '40 days 2 hours', ARRAY['open source','github','community','coding'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/opensource/1200/400', ARRAY['https://picsum.photos/seed/opensourcea/800/600','https://picsum.photos/seed/opensourceb/800/600','https://picsum.photos/seed/opensourcec/800/600'], NOW(), NOW()),

-- ── Hackathons (26-30) ────────────────────────────────────────────────────────
(gen_random_uuid(), 'HackMSU Spring 2026', '48-hour hackathon open to all students. Build anything — apps, AI tools, hardware hacks. $5,000 in prizes. Free food, swag, and mentors available throughout.', 'demo-admin-001', 'admin', 'MSU Hackathon Committee', 'in_person', 'Colvard Student Union, Main Hall', NULL, NOW() + INTERVAL '15 days', NOW() + INTERVAL '17 days', ARRAY['hackathon','coding','competition','prizes','team'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/hackmsu/1200/400', ARRAY['https://picsum.photos/seed/hackmsua/800/600','https://picsum.photos/seed/hackmsub/800/600','https://picsum.photos/seed/hackmsuc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'AI for Good Hackathon', 'Build AI-powered solutions to real-world social and environmental challenges. Partner organizations will present problem statements on Day 1.', 'demo-admin-001', 'admin', 'MSU AI Ethics Club', 'hybrid', 'Longest Student Health Center Atrium', 'https://zoom.us/j/ai-good-hack', NOW() + INTERVAL '32 days', NOW() + INTERVAL '33 days 12 hours', ARRAY['hackathon','ai','social good','competition'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/aigoodhack/1200/400', ARRAY['https://picsum.photos/seed/aigoodhacka/800/600','https://picsum.photos/seed/aigoodhackb/800/600','https://picsum.photos/seed/aigoodhackc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Agri-Tech Innovation Challenge', 'Mississippi''s agriculture meets technology. Build solutions for precision farming, supply chain, or rural connectivity. $3,000 grand prize.', 'demo-univ-001', 'university', 'College of Agriculture, MSU', 'in_person', 'Bost Building, MSU', NULL, NOW() + INTERVAL '45 days', NOW() + INTERVAL '46 days 12 hours', ARRAY['hackathon','agriculture','agritech','innovation','prize'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/agrihack/1200/400', ARRAY['https://picsum.photos/seed/agrihacka/800/600','https://picsum.photos/seed/agrihackb/800/600','https://picsum.photos/seed/agrihackc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Cybersecurity Capture the Flag (CTF)', '24-hour individual and team CTF competition. Categories: forensics, web exploitation, pwn, crypto, and miscellaneous. Certificate for all participants.', 'demo-univ-001', 'university', 'MSU Cybersecurity Lab', 'virtual', NULL, 'https://ctf.msstate.edu', NOW() + INTERVAL '19 days', NOW() + INTERVAL '20 days', ARRAY['ctf','cybersecurity','competition','hacking'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/ctfcomp/1200/400', ARRAY['https://picsum.photos/seed/ctfcompa/800/600','https://picsum.photos/seed/ctfcompb/800/600','https://picsum.photos/seed/ctfcompc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'HealthTech Hackathon 2026', 'Innovate in digital health. Build tools for patient engagement, medical imaging AI, or clinical workflow optimization. Judges from top health systems.', 'demo-admin-001', 'admin', 'MSU Center for Advanced Vehicular Systems', 'hybrid', 'Research Park, Bldg A', 'https://zoom.us/j/healthtech-hack', NOW() + INTERVAL '50 days', NOW() + INTERVAL '51 days', ARRAY['hackathon','health','medtech','ai','innovation'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/healthhack/1200/400', ARRAY['https://picsum.photos/seed/healthhacka/800/600','https://picsum.photos/seed/healthhackb/800/600','https://picsum.photos/seed/healthhackc/800/600'], NOW(), NOW()),

-- ── Research & Academic (31-42) ───────────────────────────────────────────────
(gen_random_uuid(), 'Graduate Research Symposium 2026', 'Annual showcase of graduate student research across all disciplines. Poster and oral presentation formats. Faculty judges award prizes in each college.', 'demo-admin-001', 'admin', 'MSU Graduate School', 'in_person', 'Colvard Student Union, Ballroom', NULL, NOW() + INTERVAL '23 days', NOW() + INTERVAL '23 days 8 hours', ARRAY['research','symposium','graduate','academic','poster'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/gradsymposium/1200/400', ARRAY['https://picsum.photos/seed/gradsymposiuma/800/600','https://picsum.photos/seed/gradsymposiumb/800/600','https://picsum.photos/seed/gradsymposiumc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'How to Write a Strong Research Paper', 'Tips from journal editors and senior researchers on structure, writing clarity, literature review, and the peer-review process.', 'demo-univ-001', 'university', 'MSU Writing Center', 'virtual', NULL, 'https://zoom.us/j/research-writing', NOW() + INTERVAL '13 days', NOW() + INTERVAL '13 days 90 minutes', ARRAY['research','writing','academic','publication'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/researchwriting/1200/400', ARRAY['https://picsum.photos/seed/researchwritinga/800/600','https://picsum.photos/seed/researchwritingb/800/600','https://picsum.photos/seed/researchwritingc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Computational Biology Seminar Series', 'Weekly seminar featuring research talks on bioinformatics, genomics, and computational drug discovery. This week: protein structure prediction with AlphaFold.', 'demo-univ-001', 'university', 'MSU Department of Biochemistry', 'hybrid', 'Life Sciences Building, Seminar Room', 'https://zoom.us/j/compbio', NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days 2 hours', ARRAY['biology','bioinformatics','research','seminar','alphafold'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/compbioseminar/1200/400', ARRAY['https://picsum.photos/seed/compbioseminara/800/600','https://picsum.photos/seed/compbioseminarb/800/600','https://picsum.photos/seed/compbioseminarc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'NSF Grant Writing Boot Camp', 'Learn to write compelling NSF proposals. Covers broader impacts, intellectual merit, and common pitfalls. Past reviewers share insider tips.', 'demo-admin-001', 'admin', 'MSU Office of Research', 'in_person', 'Research Park Conference Center', NULL, NOW() + INTERVAL '27 days', NOW() + INTERVAL '27 days 6 hours', ARRAY['nsf','grant','research','funding','academic'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/nsfgrant/1200/400', ARRAY['https://picsum.photos/seed/nsfgranta/800/600','https://picsum.photos/seed/nsfgrantb/800/600','https://picsum.photos/seed/nsfgrantc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'PhD Student Orientation: Research Resources', 'Overview of library databases, HPC clusters, lab safety, IRB protocols, and funding opportunities for incoming PhD students.', 'demo-admin-001', 'admin', 'MSU Graduate School', 'in_person', 'Mitchell Memorial Library, Auditorium', NULL, NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day 4 hours', ARRAY['phd','orientation','research','graduate','resources'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/phdorient/1200/400', ARRAY['https://picsum.photos/seed/phdorienta/800/600','https://picsum.photos/seed/phdorientb/800/600','https://picsum.photos/seed/phdorientc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Thesis Defense: Deep Learning for Remote Sensing', 'Public thesis defense by Priya Nair (PhD candidate). Committee: Dr. Johnson, Dr. Kim, Dr. Patel. Reception to follow in the department lounge.', 'demo-univ-001', 'university', 'MSU Electrical & Computer Engineering', 'in_person', 'McCain Hall 205', NULL, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days 2 hours', ARRAY['thesis','defense','deep learning','remote sensing','phd'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/thesisdefense/1200/400', ARRAY['https://picsum.photos/seed/thesisdefensea/800/600','https://picsum.photos/seed/thesisdefenseb/800/600','https://picsum.photos/seed/thesisdefensec/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Introduction to High-Performance Computing', 'Hands-on intro to MSU''s HPCC clusters. Topics: SLURM job scheduling, parallel computing, MPI basics, and GPU programming.', 'demo-univ-001', 'university', 'MSU High Performance Computing', 'hybrid', 'HPC Center, Training Room', 'https://zoom.us/j/hpc-intro', NOW() + INTERVAL '31 days', NOW() + INTERVAL '31 days 4 hours', ARRAY['hpc','parallel computing','gpu','slurm','research'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/hpcintro/1200/400', ARRAY['https://picsum.photos/seed/hpcintroa/800/600','https://picsum.photos/seed/hpcintrob/800/600','https://picsum.photos/seed/hpcintroc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Ethics in AI Research Panel', 'Researchers and ethicists discuss bias in algorithms, responsible AI deployment, data privacy, and the societal impact of AI systems.', 'demo-admin-001', 'admin', 'MSU AI Ethics Initiative', 'virtual', NULL, 'https://zoom.us/j/ai-ethics', NOW() + INTERVAL '17 days', NOW() + INTERVAL '17 days 2 hours', ARRAY['ai','ethics','research','bias','panel'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/aiethics/1200/400', ARRAY['https://picsum.photos/seed/aiethicsa/800/600','https://picsum.photos/seed/aiethicsb/800/600','https://picsum.photos/seed/aiethicsc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Peer Review Workshop: Give Better Feedback', 'Interactive session on how to review manuscripts constructively. Practice with real anonymized submissions across STEM disciplines.', 'demo-univ-001', 'university', 'MSU Writing Center', 'in_person', 'Allen Hall 105', NULL, NOW() + INTERVAL '38 days', NOW() + INTERVAL '38 days 2 hours', ARRAY['peer review','writing','academic','research'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/peerreview/1200/400', ARRAY['https://picsum.photos/seed/peerreviewa/800/600','https://picsum.photos/seed/peerreviewb/800/600','https://picsum.photos/seed/peerreviewc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Using AI Tools in Your Research (Ethically)', 'ChatGPT, Claude, Grammarly, Elicit — what is allowed? How to cite AI use? Workshop on the responsible use of AI in academic research.', 'demo-univ-001', 'university', 'MSU Graduate School', 'virtual', NULL, 'https://zoom.us/j/ai-research-ethics', NOW() + INTERVAL '42 days', NOW() + INTERVAL '42 days 90 minutes', ARRAY['ai','research','ethics','chatgpt','academic'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/airesearch/1200/400', ARRAY['https://picsum.photos/seed/airesearcha/800/600','https://picsum.photos/seed/airesearchb/800/600','https://picsum.photos/seed/airesearchc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Entrepreneurship for Researchers: From Lab to Startup', 'How to commercialize your research. IP protection, university spin-off programs, SBIR grants, and finding co-founders.', 'demo-admin-001', 'admin', 'MSU Entrepreneurship Center', 'hybrid', 'Research Park, Innovation Hub', 'https://teams.microsoft.com/startup-research', NOW() + INTERVAL '47 days', NOW() + INTERVAL '47 days 3 hours', ARRAY['entrepreneurship','research','startup','ip','sbir'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/labtostartup/1200/400', ARRAY['https://picsum.photos/seed/labtostartupa/800/600','https://picsum.photos/seed/labtostartupb/800/600','https://picsum.photos/seed/labtostartupc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Statistics for Non-Statisticians', 'Essential stats for researchers in biology, psychology, social sciences, and engineering. ANOVA, regression, power analysis — no math degree required.', 'demo-univ-001', 'university', 'MSU Department of Statistics', 'in_person', 'Allen Hall 303', NULL, NOW() + INTERVAL '29 days', NOW() + INTERVAL '29 days 3 hours', ARRAY['statistics','research','data analysis','methods'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/statsworkshop/1200/400', ARRAY['https://picsum.photos/seed/statsworkshopa/800/600','https://picsum.photos/seed/statsworkshopb/800/600','https://picsum.photos/seed/statsworkshopc/800/600'], NOW(), NOW()),

-- ── Networking & Alumni (43-50) ───────────────────────────────────────────────
(gen_random_uuid(), 'Alumni Industry Night: Class of 2020–2024', 'Reconnect with recent MSU alumni now working at top companies. Small group conversations over dinner. Great for referrals and mentorship.', 'demo-admin-001', 'admin', 'MSU Alumni Association', 'in_person', 'The Bully'' Pub, Starkville MS', NULL, NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days 3 hours', ARRAY['alumni','networking','mentorship','career'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/alumninight/1200/400', ARRAY['https://picsum.photos/seed/alumninighta/800/600','https://picsum.photos/seed/alumninightb/800/600','https://picsum.photos/seed/alumninightc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Speed Networking: Meet 20 People in 60 Minutes', 'Structured speed networking session. Each round is 3 minutes — practice your elevator pitch and expand your professional network fast.', 'demo-admin-001', 'admin', 'MSU Graduate Student Association', 'in_person', 'Colvard Student Union 302', NULL, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days 2 hours', ARRAY['networking','speed networking','career','professional'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/speednetwork/1200/400', ARRAY['https://picsum.photos/seed/speednetworka/800/600','https://picsum.photos/seed/speednetworkb/800/600','https://picsum.photos/seed/speednetworkc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Women in STEM Networking Brunch', 'Celebrate and connect women in science, technology, engineering, and mathematics. Keynote by Dr. Amara Osei, VP of Engineering at Salesforce.', 'demo-univ-001', 'university', 'MSU Women in STEM Alliance', 'in_person', 'Walker Hall Rooftop', NULL, NOW() + INTERVAL '20 days', NOW() + INTERVAL '20 days 3 hours', ARRAY['women','stem','networking','diversity','inclusion'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/womeninstem/1200/400', ARRAY['https://picsum.photos/seed/womeninstema/800/600','https://picsum.photos/seed/womeninstemb/800/600','https://picsum.photos/seed/womeninstemc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Black Grad Students Networking Mixer', 'Safe space for Black graduate students to connect, share experiences, and build community. Industry guests from Delta Airlines and JPMorgan Chase.', 'demo-admin-001', 'admin', 'MSU Black Graduate Student Association', 'in_person', 'Colvard Student Union Magnolia Room', NULL, NOW() + INTERVAL '15 days', NOW() + INTERVAL '15 days 3 hours', ARRAY['networking','diversity','community','graduate'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/blackgradmix/1200/400', ARRAY['https://picsum.photos/seed/blackgradmixa/800/600','https://picsum.photos/seed/blackgradmixb/800/600','https://picsum.photos/seed/blackgradmixc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Graduate Student Happy Hour', 'Monthly informal social for all graduate students. Come unwind, meet people across departments, and enjoy food and non-alcoholic drinks on us.', 'demo-admin-001', 'admin', 'MSU Graduate Student Association', 'in_person', 'HailState Brewing Co., Starkville', NULL, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days 3 hours', ARRAY['social','networking','community','graduate'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/happyhour/1200/400', ARRAY['https://picsum.photos/seed/happyhoura/800/600','https://picsum.photos/seed/happyhourb/800/600','https://picsum.photos/seed/happyhourc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Industry Mentorship Kickoff 2026', 'Get matched with a mentor from your field. This kickoff event introduces the program, sets expectations, and hosts the first mentor-mentee meeting.', 'demo-admin-001', 'admin', 'MSU Career Center', 'hybrid', 'Colvard Student Union 305', 'https://zoom.us/j/mentorship-kickoff', NOW() + INTERVAL '12 days', NOW() + INTERVAL '12 days 2 hours', ARRAY['mentorship','career','networking','professional development'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/mentorshipkick/1200/400', ARRAY['https://picsum.photos/seed/mentorshipkicka/800/600','https://picsum.photos/seed/mentorshipkickb/800/600','https://picsum.photos/seed/mentorshipkickc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Lunch with a Leader: VP at Lockheed Martin', 'Intimate lunch with Marcus Webb, VP of Engineering at Lockheed Martin. Only 15 seats available — apply on the portal. Defense, aerospace, and engineering focus.', 'demo-admin-001', 'admin', 'MSU Career Center', 'in_person', 'University Club Dining Room', NULL, NOW() + INTERVAL '24 days', NOW() + INTERVAL '24 days 2 hours', ARRAY['networking','aerospace','defense','leadership','exclusive'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/lunchwithleader/1200/400', ARRAY['https://picsum.photos/seed/lunchwithleadera/800/600','https://picsum.photos/seed/lunchwithleaderb/800/600','https://picsum.photos/seed/lunchwithleaderc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Virtual Coffee Chat: Connect with Global Alums', 'Sign up for a 20-minute one-on-one video call with an MSU alumnus in your field. Alumni in 15+ countries and 30+ industries participating.', 'demo-admin-001', 'admin', 'MSU Alumni Network', 'virtual', NULL, 'https://calendly.com/msu-alumni-coffee', NOW() + INTERVAL '3 days', NOW() + INTERVAL '30 days', ARRAY['alumni','networking','virtual','mentorship','global'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/coffeechat/1200/400', ARRAY['https://picsum.photos/seed/coffeechata/800/600','https://picsum.photos/seed/coffeechatb/800/600','https://picsum.photos/seed/coffeechatc/800/600'], NOW(), NOW()),

-- ── Mental Health & Wellness (51-55) ──────────────────────────────────────────
(gen_random_uuid(), 'Managing PhD Stress & Imposter Syndrome', 'Open discussion led by a licensed counselor on the unique mental health challenges of graduate school. Evidence-based coping strategies included.', 'demo-admin-001', 'admin', 'MSU Counseling Services', 'hybrid', 'Longest Student Health Center, Room 200', 'https://zoom.us/j/phd-stress', NOW() + INTERVAL '9 days', NOW() + INTERVAL '9 days 2 hours', ARRAY['mental health','wellness','phd','stress','counseling'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/phdstress/1200/400', ARRAY['https://picsum.photos/seed/phdstressa/800/600','https://picsum.photos/seed/phdstressb/800/600','https://picsum.photos/seed/phdstressc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Mindfulness & Meditation for Students', 'Weekly guided meditation session. No experience needed. Learn breathing techniques, body scan, and mindfulness practices to reduce academic stress.', 'demo-admin-001', 'admin', 'MSU Wellness Center', 'virtual', NULL, 'https://zoom.us/j/mindfulness', NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days 1 hour', ARRAY['mindfulness','meditation','wellness','stress','mental health'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/mindfulness/1200/400', ARRAY['https://picsum.photos/seed/mindfulnessa/800/600','https://picsum.photos/seed/mindfulnessb/800/600','https://picsum.photos/seed/mindfulnessc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Yoga on the Drill Field', 'Free outdoor yoga session for all students. All levels welcome. Bring your mat or borrow one. Rain location: Sanderson Center Studio B.', 'demo-admin-001', 'admin', 'MSU Campus Recreation', 'in_person', 'Drill Field, MSU', NULL, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days 1 hour', ARRAY['yoga','wellness','fitness','outdoor','free'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/yogadrillfield/1200/400', ARRAY['https://picsum.photos/seed/yogadrillfielda/800/600','https://picsum.photos/seed/yogadrillfieldb/800/600','https://picsum.photos/seed/yogadrillfieldc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Work-Life Balance in Graduate School', 'Panel with faculty and senior PhD students on setting boundaries, avoiding burnout, and maintaining hobbies and relationships during grad school.', 'demo-univ-001', 'university', 'MSU Graduate School', 'virtual', NULL, 'https://zoom.us/j/worklife-balance', NOW() + INTERVAL '26 days', NOW() + INTERVAL '26 days 90 minutes', ARRAY['wellness','work-life balance','graduate','mental health'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/worklifebal/1200/400', ARRAY['https://picsum.photos/seed/worklifebala/800/600','https://picsum.photos/seed/worklifebalb/800/600','https://picsum.photos/seed/worklifebalc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Financial Wellness Workshop: Student Budgeting', 'How to live on a stipend. Topics: budgeting apps, student loan strategies, taxes for international students, and investing basics.', 'demo-admin-001', 'admin', 'MSU Financial Aid Office', 'hybrid', 'Allen Hall 101', 'https://zoom.us/j/financial-wellness', NOW() + INTERVAL '34 days', NOW() + INTERVAL '34 days 2 hours', ARRAY['finance','budgeting','wellness','stipend','taxes'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/financewellness/1200/400', ARRAY['https://picsum.photos/seed/financewellnessa/800/600','https://picsum.photos/seed/financewellnessb/800/600','https://picsum.photos/seed/financewellnessc/800/600'], NOW(), NOW()),

-- ── Cultural & Community (56-62) ──────────────────────────────────────────────
(gen_random_uuid(), 'International Food Festival', 'Student organizations from 25+ countries share their cuisine and culture. Cooking demonstrations, traditional performances, and passport stamping activity.', 'demo-admin-001', 'admin', 'MSU International Student Services', 'in_person', 'Colvard Student Union Plaza', NULL, NOW() + INTERVAL '11 days', NOW() + INTERVAL '11 days 6 hours', ARRAY['culture','international','food','community','diversity'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/foodfestival/1200/400', ARRAY['https://picsum.photos/seed/foodfestivala/800/600','https://picsum.photos/seed/foodfestivalb/800/600','https://picsum.photos/seed/foodfestivalc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Lunar New Year Celebration 2026', 'Year of the Horse — celebrate with traditional food, lion dance performance, calligraphy, and lantern making. Hosted by MSU Chinese Student Association.', 'demo-admin-001', 'admin', 'MSU Chinese Student Association', 'in_person', 'Lee Hall Ballroom', NULL, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days 4 hours', ARRAY['lunar new year','culture','chinese','community','celebration'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/lunarnewyear/1200/400', ARRAY['https://picsum.photos/seed/lunarnewyeara/800/600','https://picsum.photos/seed/lunarnewyearb/800/600','https://picsum.photos/seed/lunarnewyearc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Diwali Night 2026', 'Festival of Lights! Join MSU''s Indian Student Association for an evening of traditional dance, rangoli art, sweets, and fireworks (pending university approval).', 'demo-admin-001', 'admin', 'MSU Indian Student Association', 'in_person', 'Dunn-Seiler Amphitheater', NULL, NOW() + INTERVAL '43 days', NOW() + INTERVAL '43 days 4 hours', ARRAY['diwali','indian','culture','festival','community'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/diwalinight/1200/400', ARRAY['https://picsum.photos/seed/diwalinighta/800/600','https://picsum.photos/seed/diwalinightb/800/600','https://picsum.photos/seed/diwalinightc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Graduate Student Game Night', 'Board games, card games, video games — bring your favorites or use ours. Snacks provided. Great way to decompress mid-semester.', 'demo-admin-001', 'admin', 'MSU Graduate Student Association', 'in_person', 'Colvard Student Union Game Room', NULL, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days 3 hours', ARRAY['games','social','fun','community','graduate'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/gamenight/1200/400', ARRAY['https://picsum.photos/seed/gamenighta/800/600','https://picsum.photos/seed/gamenightb/800/600','https://picsum.photos/seed/gamenightc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Mississippi Culture & History Tour', 'Guided tour of historical landmarks in Starkville and Columbus. Learn about the civil rights history and cultural heritage of Mississippi.', 'demo-admin-001', 'admin', 'MSU History Department', 'in_person', 'Departs from Hardy Hall Parking Lot', NULL, NOW() + INTERVAL '16 days', NOW() + INTERVAL '16 days 6 hours', ARRAY['history','culture','mississippi','tour','community'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/mstour/1200/400', ARRAY['https://picsum.photos/seed/mstoura/800/600','https://picsum.photos/seed/mstourb/800/600','https://picsum.photos/seed/mstourc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Movie Night: Hidden Figures Screening', 'Watch Hidden Figures followed by a panel discussion on diversity in STEM and the legacy of Katherine Johnson, Dorothy Vaughan, and Mary Jackson.', 'demo-admin-001', 'admin', 'MSU Diversity & Inclusion Office', 'in_person', 'Hull Auditorium', NULL, NOW() + INTERVAL '13 days', NOW() + INTERVAL '13 days 3 hours', ARRAY['film','diversity','stem','community','history'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/hiddenfigures/1200/400', ARRAY['https://picsum.photos/seed/hiddenfiguresa/800/600','https://picsum.photos/seed/hiddenfiguresb/800/600','https://picsum.photos/seed/hiddenfiguresc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Graduate Student Volunteer Day', 'Give back to the Starkville community. Activities include park cleanup, food bank volunteering, and tutoring local high schoolers. T-shirts and lunch provided.', 'demo-admin-001', 'admin', 'MSU Center for Community-Engaged Learning', 'in_person', 'Meets at Colvard Student Union Entrance', NULL, NOW() + INTERVAL '21 days', NOW() + INTERVAL '21 days 6 hours', ARRAY['volunteer','community','service','social'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/volunteerday/1200/400', ARRAY['https://picsum.photos/seed/volunteerdaya/800/600','https://picsum.photos/seed/volunteerdayb/800/600','https://picsum.photos/seed/volunteerdayc/800/600'], NOW(), NOW()),

-- ── Industry & Professional Development (63-70) ───────────────────────────────
(gen_random_uuid(), 'Product Management 101 for Engineers', 'What does a PM actually do? Learn product thinking, user research, roadmaps, and how to transition from engineering to product management.', 'demo-admin-001', 'admin', 'MSU Entrepreneurship Center', 'virtual', NULL, 'https://zoom.us/j/pm-101', NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days 2 hours', ARRAY['product management','career','engineering','leadership'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/productmgmt/1200/400', ARRAY['https://picsum.photos/seed/productmgmta/800/600','https://picsum.photos/seed/productmgmtb/800/600','https://picsum.photos/seed/productmgmtc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Consulting Careers: What They Don''t Tell You', 'Former McKinsey and BCG consultants share what life in consulting is really like — travel, case interviews, exit opportunities, and work-life balance.', 'demo-admin-001', 'admin', 'MSU Business School', 'hybrid', 'McCool Hall 200', 'https://zoom.us/j/consulting-panel', NOW() + INTERVAL '18 days', NOW() + INTERVAL '18 days 2 hours', ARRAY['consulting','career','mckinsey','business','panel'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/consultingcareer/1200/400', ARRAY['https://picsum.photos/seed/consultingcareera/800/600','https://picsum.photos/seed/consultingcareerb/800/600','https://picsum.photos/seed/consultingcareerc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Technical Writing for Engineers', 'Write documentation, technical reports, and proposals that non-technical stakeholders can understand. Real examples from engineering reports.', 'demo-univ-001', 'university', 'MSU English Department', 'in_person', 'Allen Hall 205', NULL, NOW() + INTERVAL '22 days', NOW() + INTERVAL '22 days 2 hours', ARRAY['writing','technical writing','communication','engineering'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/techwriting/1200/400', ARRAY['https://picsum.photos/seed/techwritinga/800/600','https://picsum.photos/seed/techwritingb/800/600','https://picsum.photos/seed/techwritingc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Leadership in Action: Student Leader Panel', 'Undergraduate and graduate student leaders share lessons from leading organizations, managing conflict, and driving change on campus.', 'demo-admin-001', 'admin', 'MSU Leadership Institute', 'in_person', 'Colvard Student Union 301', NULL, NOW() + INTERVAL '28 days', NOW() + INTERVAL '28 days 2 hours', ARRAY['leadership','student','panel','professional development'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/leaderpanel/1200/400', ARRAY['https://picsum.photos/seed/leaderpanela/800/600','https://picsum.photos/seed/leaderpanelb/800/600','https://picsum.photos/seed/leaderpanelc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Pitch Competition: Grad Student Ideas', '$2,000 for the best 5-minute business or research pitch. Open to all graduate students. Three rounds: preliminary, semi-final, and final. Apply by April 1.', 'demo-admin-001', 'admin', 'MSU Entrepreneurship Center', 'in_person', 'McCool Hall Auditorium', NULL, NOW() + INTERVAL '36 days', NOW() + INTERVAL '36 days 4 hours', ARRAY['pitch','entrepreneurship','competition','business','prize'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/pitchcomp/1200/400', ARRAY['https://picsum.photos/seed/pitchcompa/800/600','https://picsum.photos/seed/pitchcompb/800/600','https://picsum.photos/seed/pitchcompc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Public Speaking & Presentation Skills', 'Overcome public speaking anxiety and learn storytelling, slide design, and delivery techniques. Video playback and personalized feedback included.', 'demo-univ-001', 'university', 'MSU Communication Department', 'hybrid', 'Lee Hall 103', 'https://zoom.us/j/public-speaking', NOW() + INTERVAL '39 days', NOW() + INTERVAL '39 days 3 hours', ARRAY['public speaking','presentation','communication','skills'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/publicspeaking/1200/400', ARRAY['https://picsum.photos/seed/publicspeakinga/800/600','https://picsum.photos/seed/publicspeakingb/800/600','https://picsum.photos/seed/publicspeakingc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Introduction to Project Management (PMP Prep)', 'Overview of project management methodologies: Waterfall, Agile, and Scrum. Preparation tips for the PMP certification exam.', 'demo-univ-001', 'university', 'MSU Industrial Engineering', 'virtual', NULL, 'https://zoom.us/j/pmp-prep', NOW() + INTERVAL '44 days', NOW() + INTERVAL '44 days 3 hours', ARRAY['project management','pmp','agile','scrum','certification'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/pmpprep/1200/400', ARRAY['https://picsum.photos/seed/pmpprepa/800/600','https://picsum.photos/seed/pmpprepb/800/600','https://picsum.photos/seed/pmpprepc/800/600'], NOW(), NOW()),

(gen_random_uuid(), 'Design Thinking Workshop', 'Human-centered design in action. Work through a real problem using empathy maps, ideation sprints, prototyping, and user testing. Teams of 4–5 people.', 'demo-admin-001', 'admin', 'MSU Center for Entrepreneurship & Innovation', 'in_person', 'Innovation Hub, Research Park', NULL, NOW() + INTERVAL '48 days', NOW() + INTERVAL '48 days 4 hours', ARRAY['design thinking','innovation','ux','workshop','teamwork'], TRUE, 0.0, 'low', ARRAY[]::TEXT[], 'https://picsum.photos/seed/designthinking/1200/400', ARRAY['https://picsum.photos/seed/designthinkinga/800/600','https://picsum.photos/seed/designthinkingb/800/600','https://picsum.photos/seed/designthinkingc/800/600'], NOW(), NOW());

-- Verify count
SELECT COUNT(*) AS total_events_inserted FROM events;
