"""add_apartment_table

Revision ID: a1253d634e78
Revises: d1ff1a7278ba
Create Date: 2026-03-28 14:15:57.868961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1253d634e78'
down_revision: Union[str, None] = 'd1ff1a7278ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('is_furnished', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('available_from', sa.String(length=50), nullable=True),
    sa.Column('images_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('posted_by', sa.String(length=36), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartments_city'), 'apartments', ['city'], unique=False)
    op.create_index(op.f('ix_apartments_state'), 'apartments', ['state'], unique=False)
    op.drop_index('ix_internship_recommendations_internship_id', table_name='internship_recommendations')
    op.drop_index('ix_internship_recommendations_recommended_for_date', table_name='internship_recommendations')
    op.drop_index('ix_internship_recommendations_student_profile_id', table_name='internship_recommendations')
    op.drop_table('internship_recommendations')
    op.drop_index('ix_internships_company', table_name='internships')
    op.drop_index('ix_internships_posted_by', table_name='internships')
    op.drop_index('ix_internships_title', table_name='internships')
    op.drop_table('internships')
    op.drop_index('ix_student_profiles_major', table_name='student_profiles')
    op.drop_index('ix_student_profiles_university_id', table_name='student_profiles')
    op.drop_index('ix_student_profiles_user_id', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_constraint('uq_universities_keycloak_user_id', 'universities', type_='unique')
    op.drop_index('ix_universities_keycloak_user_id', table_name='universities')
    op.create_index(op.f('ix_universities_keycloak_user_id'), 'universities', ['keycloak_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_keycloak_user_id'), table_name='universities')
    op.create_index('ix_universities_keycloak_user_id', 'universities', ['keycloak_user_id'], unique=False)
    op.create_unique_constraint('uq_universities_keycloak_user_id', 'universities', ['keycloak_user_id'])
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('major', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='student_profiles_university_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='student_profiles_user_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_student_profiles_user_id', 'student_profiles', ['user_id'], unique=False)
    op.create_index('ix_student_profiles_university_id', 'student_profiles', ['university_id'], unique=False)
    op.create_index('ix_student_profiles_major', 'student_profiles', ['major'], unique=False)
    op.create_table('internships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('application_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('posted_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('majors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='internships_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_internships_title', 'internships', ['title'], unique=False)
    op.create_index('ix_internships_posted_by', 'internships', ['posted_by'], unique=False)
    op.create_index('ix_internships_company', 'internships', ['company'], unique=False)
    op.create_table('internship_recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('recommended_for_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], name='internship_recommendations_internship_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name='internship_recommendations_student_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='internship_recommendations_pkey'),
    sa.UniqueConstraint('student_profile_id', 'internship_id', 'recommended_for_date', name='uq_profile_internship_day')
    )
    op.create_index('ix_internship_recommendations_student_profile_id', 'internship_recommendations', ['student_profile_id'], unique=False)
    op.create_index('ix_internship_recommendations_recommended_for_date', 'internship_recommendations', ['recommended_for_date'], unique=False)
    op.create_index('ix_internship_recommendations_internship_id', 'internship_recommendations', ['internship_id'], unique=False)
    op.drop_index(op.f('ix_apartments_state'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_city'), table_name='apartments')
    op.drop_table('apartments')
    # ### end Alembic commands ###
